apiVersion: v1
kind: Service
metadata:
  name: multitool-service
spec:
  selector:
    app: multitool-app
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
  - name: multitool-port
    port: 8080
    targetPort: 8080
